spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5433/payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
  security:
    username: admin
    password: 1234